benchmark_root: /workspace/tingting/LIBERO/libero/libero
bddl_files: /workspace/tingting/LIBERO/libero/libero/bddl_files
init_states: /workspace/tingting/LIBERO/libero/libero/init_files
datasets: /workspace/tingting/LIBERO/datasets
assets: /workspace/tingting/LIBERO/libero/libero/assets